debug=true

rewards.recipient.name=John Doe
rewards.recipient.age=10
rewards.recipient.gender=Male
rewards.recipient.hobby=Tennis

# Logging control
logging.level.root=ERROR

logging.level.rewards=INFO
logging.level.config=DEBUG
